{
 "title": "Invidious - Companion",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Videoplayback requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Forbidden Videoplayback (403 from Youtube servers)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(invidious_companion_videoplayback_forbidden_total[$__rate_interval])",
     "legendFormat": "{{instance}} - {{method}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Successful Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(invidious_companion_innertube_successful_request_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "rate(invidious_companion_innertube_failed_request_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Player errors",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(invidious_companion_youtubejs_player_errors_total[$__rate_interval])",
     "legendFormat": "{{instance}} - {{error}}"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Unknown Status Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "rate(invidious_companion_innertube_error_status_unknown_total[$__rate_interval])",
     "legendFormat": "{{instance}} - {{error}}"
    }
   ]
  },
  {
   "title": "\"LOGIN_REQUIRED\" Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "rate(invidious_companion_innertube_error_status_loginRequired_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Reasons", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Unknown Reason Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "rate(invidious_companion_innertube_error_reason_unknown_total[$__rate_interval])",
     "legendFormat": "{{instance}} - {{error}}"
    }
   ]
  },
  {
   "title": "\"Sign in to confirm you’re not a bot.\" Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "rate(invidious_companion_innertube_error_reason_SignIn_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Subreasons", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Unknown Subreason Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "rate(invidious_companion_innertube_error_subreason_unknown_total[$__rate_interval])",
     "legendFormat": "{{instance}} - {{error}}"
    }
   ]
  },
  {
   "title": "\"This helps protect our community.\" Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "rate(invidious_companion_innertube_error_subreason_ProtectCommunity_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "poToken Generation Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "rate(invidious_companion_potoken_generation_failure_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}