[server]
port = 8282
host = "127.0.0.1"
# secret key needs to be 16 characters long or more
secret_key = "CHANGE_ME"
verify_requests = false

[cache]
enabled = true
# will get cached in /var/tmp/youtubei.js if you specify /var/tmp
# you need to change the --allow-write from deno run too
directory = "/var/tmp"

[networking]
#proxy = ""
# Enable YouTube new video format UMP
ump = false

[networking.fetch]
timeout_ms = 10000

[networking.fetch.retry]
enabled = true
times = 3
initial_debounce = 500
debounce_multiplier = 2

[jobs]

[jobs.youtube_session]
po_token_enabled = true
frequency = "*/5 * * * *"

[youtube_session]
oauth_enabled = false
cookies = ""
