name: Testing

on:
  pull_request:
    branches: [master]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v6

      - name: Checkout binaries repo
        uses: actions/checkout@v6
        with:
          repository: iv-org/binaries
          path: ci-binaries
        
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Verify formatting
        run: deno task format

      - name: Verify typing
        run: deno task check
      
      - name: Run linter
        run: deno task lint

      - name: Run tests x4 times (IP may be banned)
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 4
          command: |
            ci-binaries/opera-proxy-amd64 &
            PROXY_PID=$!
            sleep 3s
            curl -s -x http://127.0.0.1:18080 --retry 5 --retry-delay 2 --retry-connrefused https://check.torproject.org/api/ip; echo 
            rm -rf /var/tmp/youtubei.js
            PROXY=http://127.0.0.1:18080 deno task test
            kill $PROXY_PID
