name: Linter

on:
  pull_request:
    branches: [master]
  push:
    branches:
      - add-tests  # Trigger on pushes to master branch

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4
        
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Verify formatting
        run: deno fmt --check src/**

      - name: Verify typing
        run: deno check src/**
      
      - name: Run linter
        run: deno lint

      # - name: Install and run tor
      #   uses: tor-actions/setup-tor@main
      #   with:
      #     daemon: true
      #     port: 9150

      # - name: Run linter
      #   run: bash src/tests/wait_tor_ready.sh

      - name: Run tests
        run: deno task test
