name: Testing

on:
  pull_request:
    branches: [master]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v6
        
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Verify formatting
        run: deno task format

      - name: Verify typing
        run: deno task check
      
      - name: Run linter
        run: deno task lint

      - name: Checkout binaries repo
        uses: actions/checkout@v6
        with:
          repository: iv-org/binaries
          path: ci-binaries

      - name: Install and run tor
        uses: tor-actions/setup-tor@main
        with:
          daemon: true
          port: 9150
          config: |
            ExcludeExitNodes {us}
            StrictNodes 1

      - name: Run tests x4 times (IP may be banned) with opera-proxy
        uses: nick-fields/retry@v3
        id: opera_proxy
        with:
          timeout_minutes: 5
          max_attempts: 4
          command: |
            ci-binaries/opera-proxy-amd64 &
            PROXY_PID=$!
            sleep 3s
            curl -s -x http://127.0.0.1:18080 --retry 5 --retry-delay 2 --retry-connrefused https://check.torproject.org/api/ip; echo 
            rm -rf /var/tmp/youtubei.js
            PROXY=http://127.0.0.1:18080 deno task test
            TEST_EXIT=$?
            kill $PROXY_PID
            exit $TEST_EXIT

      - name: Run tests x8 times (IP may be banned) with tor if opera failed
        uses: nick-fields/retry@v3
        if: failure() && steps.opera_proxy.outcome == 'failure'
        with:
          timeout_minutes: 5
          max_attempts: 8
          command: |
            sudo pkill -HUP tor
            curl -s --socks5 127.0.0.1:9150 https://check.torproject.org/api/ip; echo 
            rm -rf /var/tmp/youtubei.js
            PROXY=socks5://127.0.0.1:9150 deno task test
